-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

-- APAGA TUDO DO SCHEMA PUBLIC
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;



CREATE TABLE public.account_balance_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  adjustment_date date NOT NULL,
  balance numeric NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['initial'::text, 'reconciliation'::text, 'correction'::text])),
  notes text,
  starts_controlled_period boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT account_balance_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT account_balance_adjustments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_balance_adjustments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'outros'::text,
  balance numeric NOT NULL DEFAULT 0.00,
  color text DEFAULT '#3b82f6'::text,
  icon text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  yield_rate double precision DEFAULT 0,
  last_yield_date date,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.asset_prices (
  ticker character varying NOT NULL,
  date date NOT NULL,
  close_price numeric NOT NULL,
  CONSTRAINT asset_prices_pkey PRIMARY KEY (ticker, date)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  icon text DEFAULT 'tag'::text,
  color text DEFAULT '#94a3b8'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.credit_card_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  credit_card_id uuid NOT NULL,
  reference_month integer NOT NULL CHECK (reference_month >= 1 AND reference_month <= 12),
  reference_year integer NOT NULL CHECK (reference_year >= 2000),
  closing_date date NOT NULL,
  due_date date NOT NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  paid_amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text, 'paid'::text, 'overdue'::text, 'partial'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_card_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT credit_card_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT credit_card_invoices_credit_card_id_fkey FOREIGN KEY (credit_card_id) REFERENCES public.credit_cards(id)
);
CREATE TABLE public.credit_card_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  credit_card_id uuid NOT NULL,
  invoice_id uuid,
  category_id uuid,
  description text NOT NULL,
  amount numeric NOT NULL,
  transaction_date date NOT NULL,
  is_installment boolean DEFAULT false,
  installment_number integer,
  total_installments integer,
  parent_transaction_id uuid,
  transaction_type text NOT NULL DEFAULT 'purchase'::text CHECK (transaction_type = ANY (ARRAY['purchase'::text, 'refund'::text, 'adjustment'::text, 'fee'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subcategory_id uuid,
  group_id uuid,
  CONSTRAINT credit_card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT credit_card_transactions_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id),
  CONSTRAINT credit_card_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT credit_card_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.credit_card_invoices(id),
  CONSTRAINT credit_card_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT credit_card_transactions_parent_transaction_id_fkey FOREIGN KEY (parent_transaction_id) REFERENCES public.credit_card_transactions(id),
  CONSTRAINT credit_card_transactions_credit_card_id_fkey FOREIGN KEY (credit_card_id) REFERENCES public.credit_cards(id)
);
CREATE TABLE public.credit_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  brand text NOT NULL DEFAULT 'other'::text,
  last_4_digits text,
  limit_amount numeric NOT NULL DEFAULT 0,
  closing_day integer NOT NULL CHECK (closing_day >= 1 AND closing_day <= 31),
  due_day integer NOT NULL CHECK (due_day >= 1 AND due_day <= 31),
  color text DEFAULT '#0f172a'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  account_id uuid,
  CONSTRAINT credit_cards_pkey PRIMARY KEY (id),
  CONSTRAINT credit_cards_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT credit_cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.investment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investment_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  date date NOT NULL,
  quantity numeric NOT NULL,
  price numeric NOT NULL,
  total_amount numeric NOT NULL,
  fees numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT investment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT investment_transactions_investment_id_fkey FOREIGN KEY (investment_id) REFERENCES public.investments(id)
);
CREATE TABLE public.investments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  account_id uuid NOT NULL,
  ticker character varying NOT NULL,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  average_price numeric NOT NULL DEFAULT 0,
  current_price numeric NOT NULL DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT investments_pkey PRIMARY KEY (id),
  CONSTRAINT investments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.liquidity_yields (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  date date NOT NULL,
  base_amount numeric NOT NULL,
  yield_amount numeric NOT NULL,
  rate_applied double precision NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liquidity_yields_pkey PRIMARY KEY (id),
  CONSTRAINT liquidity_yields_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.payables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL,
  due_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'cancelled'::text])),
  paid_at timestamp with time zone,
  transaction_id uuid,
  category_id uuid,
  subcategory_id uuid,
  recurrence_strategy text DEFAULT 'single'::text CHECK (recurrence_strategy = ANY (ARRAY['single'::text, 'installment'::text, 'fixed'::text])),
  installment_number integer,
  total_installments integer,
  parent_id uuid,
  barcode text,
  beneficiary text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_method_id uuid,
  CONSTRAINT payables_pkey PRIMARY KEY (id),
  CONSTRAINT payables_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT payables_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id),
  CONSTRAINT payables_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.payables(id),
  CONSTRAINT payables_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT payables_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payables_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid DEFAULT auth.uid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['PIX'::text, 'CASH'::text, 'CREDIT_CARD'::text, 'DEBIT_CARD'::text, 'BANK_TRANSFER'::text, 'BOLETO'::text, 'AUTOMATIC'::text, 'INTERNAL_TRANSFER'::text, 'OTHER'::text])),
  is_active boolean NOT NULL DEFAULT true,
  allows_income boolean DEFAULT true,
  allows_expense boolean DEFAULT true,
  allows_transfer boolean NOT NULL DEFAULT false,
  affects_balance boolean NOT NULL DEFAULT true,
  affects_credit_card boolean NOT NULL DEFAULT false,
  affects_invoice boolean NOT NULL DEFAULT false,
  is_internal boolean NOT NULL DEFAULT false,
  icon character varying,
  sort_order integer DEFAULT 0,
  requires_bank_account boolean DEFAULT true,
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promo_codes (
  code character varying NOT NULL,
  plan_type character varying NOT NULL,
  duration_days integer NOT NULL,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promo_codes_pkey PRIMARY KEY (code)
);
CREATE TABLE public.subcategories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT subcategories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  account_id uuid,
  destination_account_id uuid,
  category_id uuid,
  subcategory_id uuid,
  description text NOT NULL,
  amount numeric NOT NULL,
  type USER-DEFINED NOT NULL CHECK (type = ANY (ARRAY['receita'::tipo_transacao, 'despesa'::tipo_transacao, 'transferencia'::tipo_transacao])),
  date date NOT NULL DEFAULT CURRENT_DATE,
  is_paid boolean DEFAULT true,
  notes text,
  attachment_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_method_id uuid,
  credit_card_id uuid,
  installment_number integer,
  total_installments integer,
  credit_card_invoice_id uuid,
  payable_id uuid,
  related_transaction_id uuid,
  is_historical boolean DEFAULT false,
  is_adjustment boolean DEFAULT false,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT transactions_destination_account_id_fkey FOREIGN KEY (destination_account_id) REFERENCES public.accounts(id),
  CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT transactions_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id),
  CONSTRAINT transactions_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES public.payables(id),
  CONSTRAINT transactions_related_transaction_id_fkey FOREIGN KEY (related_transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT transactions_credit_card_id_fkey FOREIGN KEY (credit_card_id) REFERENCES public.credit_cards(id),
  CONSTRAINT transactions_credit_card_invoice_id_fkey FOREIGN KEY (credit_card_invoice_id) REFERENCES public.credit_card_invoices(id),
  CONSTRAINT fk_transactions_invoice FOREIGN KEY (credit_card_invoice_id) REFERENCES public.credit_card_invoices(id),
  CONSTRAINT transactions_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  email text NOT NULL UNIQUE,
  subscription_plan USER-DEFINED NOT NULL DEFAULT 'free'::subscription_plan_type_v2,
  subscription_status USER-DEFINED NOT NULL DEFAULT 'free'::subscription_status,
  subscription_started_at timestamp with time zone,
  subscription_ends_at timestamp with time zone,
  trial_ends_at timestamp with time zone DEFAULT (now() + '14 days'::interval),
  last_payment_date timestamp with time zone,
  next_billing_date timestamp with time zone,
  payment_method text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  email_verified boolean NOT NULL DEFAULT false,
  onboarding_completed boolean NOT NULL DEFAULT false,
  stripe_customer_id text,
  stripe_subscription_id text,
  primary_credit_card_id uuid,
  primary_card_locked boolean DEFAULT false,
  base_plan USER-DEFINED DEFAULT 'free'::subscription_plan_type_v2,
  is_temp_access boolean DEFAULT false,
  temp_access_expires_at timestamp with time zone,
  temp_access_origin character varying,
  used_promo_code character varying,
  subscription_start_date timestamp with time zone,
  subscription_due_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  billing_cycle character varying DEFAULT 'monthly'::character varying,
  avatar_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_primary_card FOREIGN KEY (primary_credit_card_id) REFERENCES public.credit_cards(id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);